
package View;

import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import config.Conexion;
import javax.swing.table.DefaultTableModel;

public class adminconductor extends javax.swing.JFrame {

   Conexion con1 = new Conexion();
   Connection conet;
   DefaultTableModel modeloA;
   DefaultTableModel modeloB;
   Statement st;
   ResultSet rs;
   
   
    int xMouse, yMouse;

    public adminconductor() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/newlogo.png")).getImage());
        this.Soli.setVisible(false);
        this.vertable.setVisible(false);
        this.aceptar.setVisible(false);
        this.rechazar.setVisible(false);
        consultarA();
        consultarB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rechazar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        vertable = new javax.swing.JButton();
        solicitudes = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        Soli = new javax.swing.JScrollPane();
        TableA = new javax.swing.JTable();
        Tablacoductor = new javax.swing.JScrollPane();
        TableB = new javax.swing.JTable();
        fondoL = new javax.swing.JLabel();
        CURSOR = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rechazar.png"))); // NOI18N
        rechazar.setBorder(null);
        rechazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechazarActionPerformed(evt);
            }
        });
        jPanel1.add(rechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 100, -1));

        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        eliminar.setBorder(null);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 100, -1));

        vertable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VertablaC.png"))); // NOI18N
        vertable.setBorder(null);
        vertable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vertable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertableActionPerformed(evt);
            }
        });
        jPanel1.add(vertable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, -1));

        solicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/versolicitar.png"))); // NOI18N
        solicitudes.setBorder(null);
        solicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitudesActionPerformed(evt);
            }
        });
        jPanel1.add(solicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, -1));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar2.png"))); // NOI18N
        guardar.setBorder(null);
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 100, -1));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar (2).png"))); // NOI18N
        regresar.setBorder(null);
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, -1));

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Aceptar.png"))); // NOI18N
        aceptar.setBorder(null);
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 100, -1));

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        modificar.setBorder(null);
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 100, -1));

        TableA.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        TableA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "ID", "SOLICITUD"
            }
        ));
        TableA.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Soli.setViewportView(TableA);

        jPanel1.add(Soli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 420, 290));

        TableB.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        TableB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "RUTA", "H_SALIDA", "H_ENTRADA", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableB.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tablacoductor.setViewportView(TableB);

        jPanel1.add(Tablacoductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 420, 290));

        fondoL.setBackground(new java.awt.Color(255, 255, 255));
        fondoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MYE.png"))); // NOI18N
        fondoL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(fondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 620, 540));

        CURSOR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CURSORMouseDragged(evt);
            }
        });
        CURSOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CURSORMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CURSORMousePressed(evt);
            }
        });
        jPanel1.add(CURSOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CURSORMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_CURSORMouseDragged

    private void CURSORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMouseClicked

    }//GEN-LAST:event_CURSORMouseClicked

    private void CURSORMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();


    }//GEN-LAST:event_CURSORMousePressed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

    }//GEN-LAST:event_guardarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Admin ver = new Admin();
        ver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        Conductor ver = new Conductor();
        ver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarActionPerformed

    private void solicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitudesActionPerformed
        this.Soli.setVisible(true);
        this.Tablacoductor.setVisible(false);
        this.vertable.setVisible(true);
        this.aceptar.setVisible(true);
        this.rechazar.setVisible(true);
        this.aceptar.setVisible(true);
        this.modificar.setVisible(false);
        this.eliminar.setVisible(false);
    }//GEN-LAST:event_solicitudesActionPerformed

    private void vertableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertableActionPerformed
        this.vertable.setVisible(false);
        this.Soli.setVisible(false);
        this.Tablacoductor.setVisible(true);
        this.aceptar.setVisible(false);
        this.rechazar.setVisible(false);
        this.modificar.setVisible(true);
        this.eliminar.setVisible(true);
    }//GEN-LAST:event_vertableActionPerformed

    private void rechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechazarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechazarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminconductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminconductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminconductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminconductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminconductor().setVisible(true);
            }
        });
    }
    
    void consultarA(){
        String sql="SELECT * FROM `datosc` WHERE 1";
        
        try {
            conet= con1.gConnection();
            st=conet.createStatement();
            rs=st.executeQuery(sql);
            Object[] datos = new Object[3];
            modeloA=(DefaultTableModel) TableA.getModel();
            while (rs.next()) {                
                datos [0] = rs.getInt("ID");
                datos [1] = rs.getString("NOMBRE");
                datos [2] = rs.getString("SOLICITUD");
                
                modeloA.addRow(datos);
            }
            TableA.setModel(modeloA);
            
        } catch (Exception e) {
        }
    }
    
     void consultarB(){
        String sql="SELECT * FROM `conductores` WHERE 1";
        
        try {
            conet= con1.gConnection();
            st=conet.createStatement();
            rs=st.executeQuery(sql);
            Object[] datos = new Object[5];
            modeloB=(DefaultTableModel) TableB.getModel();
            while (rs.next()) {                
                  datos [0] = rs.getString("nombre_empresa");
                  datos [1] = rs.getString("ruta");
                  datos [2] = rs.getTime("hora_salida");
                  datos [3] = rs.getTime("hora_entrada");
                  datos [4] = rs.getString("estado");
                
                modeloB.addRow(datos);
            }
            TableB.setModel(modeloB);
            
        } catch (Exception e) {
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CURSOR;
    private javax.swing.JScrollPane Soli;
    private javax.swing.JScrollPane Tablacoductor;
    private javax.swing.JTable TableA;
    private javax.swing.JTable TableB;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fondoL;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton rechazar;
    private javax.swing.JButton regresar;
    private javax.swing.JButton solicitudes;
    private javax.swing.JButton vertable;
    // End of variables declaration//GEN-END:variables
}
