package View;


import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;

import javax.swing.JFileChooser;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;

import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;

import  java.sql.PreparedStatement;
import java.sql.SQLException;
import config.Conexion;
import java.sql.Connection;


public class Perfil extends javax.swing.JFrame {
    
private String nombreyapellidosText = "";
private String edadText = "";
private String correoText = "";
private String telefonoText = "";
private String identificacionText = "";
private String informacionServicio;
    
   
    Icon alerta = new ImageIcon(getClass().getResource("/imagenes/CORRECTO.png"));
    Icon soli = new ImageIcon(getClass().getResource("/imagenes/solicitud.png"));
    Icon ok = new ImageIcon(getClass().getResource("/imagenes/ok.png"));
    Icon cancelar = new ImageIcon(getClass().getResource("/imagenes/cancelar.png"));
    Icon enviar = new ImageIcon(getClass().getResource("/imagenes/enviar.png"));
    int xMouse, yMouse;

    public Perfil() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/newlogo.png")).getImage());

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
   
        
        nombreyapellidos.setText(nombreyapellidosText);
        edad.setText(edadText);
        Correo.setText(correoText);
        Telefono.setText(telefonoText);
        identificacion.setText(identificacionText);
    }
    
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreyapellidos = new javax.swing.JTextPane();
        edad = new javax.swing.JTextPane();
        Correo = new javax.swing.JTextPane();
        Telefono = new javax.swing.JTextPane();
        identificacion = new javax.swing.JTextPane();
        regresar = new javax.swing.JButton();
        servicio = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        subirfoto = new javax.swing.JButton();
        Foto = new javax.swing.JLabel();
        fondoL = new javax.swing.JLabel();
        CURSOR = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreyapellidos.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        nombreyapellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombreyapellidos.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(nombreyapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 190, 20));

        edad.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        edad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edad.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 190, 20));

        Correo.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        Correo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Correo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 285, 300, 20));

        Telefono.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        Telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Telefono.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 245, 190, 20));

        identificacion.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        identificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        identificacion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 190, 20));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar (2).png"))); // NOI18N
        regresar.setBorder(null);
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        servicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicio.png"))); // NOI18N
        servicio.setBorder(null);
        servicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioActionPerformed(evt);
            }
        });
        jPanel1.add(servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 100, -1));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GUARDAR.png"))); // NOI18N
        guardar.setBorder(null);
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 100, -1));

        subirfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subirfoto.png"))); // NOI18N
        subirfoto.setBorder(null);
        subirfoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subirfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirfotoActionPerformed(evt);
            }
        });
        jPanel1.add(subirfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 100, -1));
        jPanel1.add(Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 155, 153));

        fondoL.setBackground(new java.awt.Color(255, 255, 255));
        fondoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perfil.png"))); // NOI18N
        fondoL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(fondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 620, 540));

        CURSOR.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CURSORMouseDragged(evt);
            }
        });
        CURSOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CURSORMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CURSORMousePressed(evt);
            }
        });
        jPanel1.add(CURSOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CURSORMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_CURSORMouseDragged

    private void CURSORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMouseClicked

    }//GEN-LAST:event_CURSORMouseClicked

    private void CURSORMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURSORMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();


    }//GEN-LAST:event_CURSORMousePressed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Menu verU = new Menu();
        verU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioActionPerformed
    JDialog cuadro = new JDialog();
    cuadro.setUndecorated(true);
    cuadro.setBackground(new Color(0, 0, 0, 0));

    JPanel panel = new JPanel();
    panel.setBackground(new Color(0, 0, 0, 0));
    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

    JLabel fondo = new JLabel(soli);
    panel.add(fondo);

    JTextField info = new JTextField();
    info.setBounds(30, 50, 290, 150);
    fondo.add(info);

    JButton en = new JButton(enviar);
    en.setBorderPainted(false);
    en.setContentAreaFilled(false);
    en.setFocusPainted(false);
    en.setBounds(100, 200, 60, 40);
    en.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Almacena el texto ingresado en el JTextField en la variable informacionServicio
            informacionServicio = info.getText();
            cuadro.dispose(); // Cierra el cuadro de diálogo después de guardar la información
            
        }
    });
    fondo.add(en);

    JButton ce = new JButton(cancelar);
    ce.setBorderPainted(false);
    ce.setContentAreaFilled(false);
    ce.setFocusPainted(false);
    ce.setBounds(170, 200, 60, 40);
    ce.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            cuadro.dispose();
        }
    });
    fondo.add(ce);

    cuadro.add(panel);
    cuadro.pack();
    cuadro.setLocationRelativeTo(null);
    cuadro.setVisible(true);
    }//GEN-LAST:event_servicioActionPerformed


    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
    
// Guardar los valores de los campos de texto en las variables de clase
    nombreyapellidosText = nombreyapellidos.getText();
    edadText = edad.getText();
    correoText = Correo.getText();
    telefonoText = Telefono.getText();
    identificacionText = identificacion.getText();

    {
        AudioClip musica = java.applet.Applet.newAudioClip(getClass().getResource("/sonido/notificacion.wav"));
        musica.play();
        JDialog dialogo = new JDialog();
        dialogo.setUndecorated(true);
        dialogo.setBackground(new Color(0, 0, 0, 0));

        JButton okis = new JButton(ok);
        okis.setBorderPainted(false);
        okis.setContentAreaFilled(false);
        okis.setFocusPainted(false);
        okis.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialogo.dispose();
            }
        });

        dialogo.add(okis);
        dialogo.add(new JLabel(alerta));
        okis.setBounds(130, 150, 60, 40);
        dialogo.pack();
        dialogo.setLocationRelativeTo(null);
        dialogo.setVisible(true);

        // Obtener los datos de nombre y apellido y la identificación
        String nombreApellidos = nombreyapellidos.getText();
        String identificacionTexto = identificacion.getText();

        // Instanciar la conexión a la base de datos
        Conexion conexion = new Conexion();
        Connection con = conexion.gConnection();

        try {
            // Preparar la consulta SQL para insertar los datos
            String query = "INSERT INTO datosu (NOMBRE, ID, SOLICITUD) VALUES (?, ?, ?)";
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, nombreApellidos);
            preparedStatement.setString(2, identificacionTexto);
            preparedStatement.setString(3, informacionServicio);

            // Ejecutar la consulta
            preparedStatement.executeUpdate();

            // Cerrar la declaración y la conexión
            preparedStatement.close();
            con.close();
        } catch (SQLException ex) {
            System.err.println("Error al guardar datos en la base de datos: " + ex);
        }
    }

    }//GEN-LAST:event_guardarActionPerformed

    private void subirfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirfotoActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {

                Image image = ImageIO.read(selectedFile);

                Image scaledImage = image.getScaledInstance(Foto.getWidth(), Foto.getHeight(), Image.SCALE_DEFAULT);

                Foto.setIcon(new ImageIcon(scaledImage));
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_subirfotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CURSOR;
    private javax.swing.JTextPane Correo;
    private javax.swing.JLabel Foto;
    private javax.swing.JTextPane Telefono;
    private javax.swing.JTextPane edad;
    private javax.swing.JLabel fondoL;
    private javax.swing.JButton guardar;
    private javax.swing.JTextPane identificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane nombreyapellidos;
    private javax.swing.JButton regresar;
    private javax.swing.JButton servicio;
    private javax.swing.JButton subirfoto;
    // End of variables declaration//GEN-END:variables
}
